name: full-test-suite
on: [push, pull_request]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1      
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Install Flutter Deps
        working-directory: ./app
        run:  flutter pub get
      - name: Exit if the directory changes
        working-directory: ./app
        run:  dart format --output=none --set-exit-if-chaned .
      - name: Run Dart Analysis
        working-directory: ./app
        run:  dart analyze
      - name: Run Dart tests
        working-directory: ./app
        run : dart test --coverage="./coverage/dart"
      - name: Run Flutter analysis
        working-directory: ./app
        run:  flutter analyze
      - name: Run Flutter Tests
        working-directory: ./app
        run: flutter test --coverage="./coverage/flutter"
