name: full-test-suite
on: [push, pull_request]

jobs:
  widget-tests:
    runs-on: ubuntu-latest
    strategy:      
      matrix:
        api-level: 
          - 34
      fail-fast: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1      
      - name: Install Flutter Deps
        working-directory: ./pocket_therapist
        run:  flutter pub get
      - name: Run Flutter analysis
        working-directory: ./pocket_therapist
        run:  flutter analyze
      - name: Find test folders
        id: check-folder
        run: |
          ls -la
          pwd
          if [ -d "./pocket_therapist/test" ]; then
            echo "unit_test_folder=true" >> "$GITHUB_ENV"
          else
            echo "unit_test_folder=false" >> "$GITHUB_ENV"
          fi

          if [ -d "./pocket_therapist/integraton_test" ]; then
            echo "integraton_test_folder=true" >> "$GITHUB_ENV"
          else
            echo "integraton_test_folder=false" >> "$GITHUB_ENV"
          fi

      - name: Run Widget Tests
        run: |
          cd ./pocket_therapist/
          if $unit_test_folder; then
            flutter test --branch-coverage
            echo "Running tests..."
          else 
            echo "No tests found, not running."
          fi
          cd ..

      - name: Run integration tests
        if: steps.check-folder.outputs.integration_test_folder == 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:          
          api-level: ${{ matrix.api-level }}
          arch: x86_64          
          profile: Pixel 7
          script: flutter test integration_test --branch-coverage --merge-coverage

      - name: Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./pocket_therapist/coverage/lcov.info
          name: code-coverage
