name: full-test-suite
on: [push, pull_request]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1      
      - name: Install Flutter Deps
        working-directory: ./app
        run:  flutter pub get
      - name: Run Flutter analysis
        working-directory: ./app
        run:  flutter analyze
      - name: Run Flutter Tests
        working-directory: ./app
        run: flutter test --branch-coverage
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1.0.0
      - name: Report Code Coverage
        uses: zgosalvez/github-actions-report-lcov@v3.1.8
        with:
          working-directory: ./app/coverage
          coverage-files: lcov.info
          minimum-coverage: 95
          artifact-name: code-coverage-report
          update-comment: true
