name: full-test-suite
on: [push, pull_request]

env:
  TEST: 0

jobs:
  full-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
 
      - name: Install Flutter Deps
        working-directory: ./pocket_therapist
        run:  flutter pub get > /dev/null
 
      - name: Run Flutter analysis
        working-directory: ./pocket_therapist
        run:  flutter analyze

      - name: Find test folders
        id: check-folder
        run: |
          if [ -d "./pocket_therapist/test" ]; then
            echo "TEST=true" >> "$GITHUB_ENV"
          fi
  
      - name: Run Widget Tests
        working-directory: ./pocket_therapist
        run: |
          if $TEST; then
            flutter test --merge-coverage --branch-coverage --timeout "5m"
          else
            echo "No tests found, not running."
          fi
 
      - name: Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./pocket_therapist/coverage/lcov.info
          name: code-coverage
 
