name: full-test-suite
on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1      
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Install Flutter Deps
        working-directory: ./app
        run:  flutter pub get
      - name: Run Flutter analysis
        working-directory: ./app
        run:  flutter analyze
      - name: Run Flutter Tests
        working-directory: ./app
        run: flutter test --branch-coverage
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/lcov.info
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80 90'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
