name: full-test-suite
on: [pull_request]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1      
      - name: Install Flutter Deps
        working-directory: ./app
        run:  flutter pub get
      - name: Install genhtml for CI reporting
        run: sudo apt-get install -y genhtml
      - name: Run Flutter analysis
        working-directory: ./app
        run:  flutter analyze
      - name: Run Flutter Tests
        working-directory: ./app
        run: flutter test --branch-coverage
      - name: Report LCOV
        uses: zgosalvez/github-actions-report-lcov@v3.1.8
        with:
          working-directory: ./app/coverage
          coverage-files: ./*.info
          update-comment: true
          minimum-coverage: 90
            
