name: full-test-suite
on: [push, pull_request]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1      
      - name: Install Flutter Deps
        working-directory: ./app
        run:  flutter pub get
      - name: Run Flutter analysis
        working-directory: ./app
        run:  flutter analyze
      - name: Run Flutter Tests
        working-directory: ./app
        run: flutter test --branch-coverage
      - name: Codecov
        uses: codecov/codecov-action@v4.0.0-beta.3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./app/coverage/lcov.info
          name: code-coverage
          verbose: true
          
